# Dependabot設定ファイル
# 依存パッケージの自動更新を月次で実行します

version: 2
updates:
  # Maven依存関係の更新設定
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    # セマンティックバージョニングに基づく更新設定
    versioning-strategy: "increase"
    # PRに自動的に追加するラベル
    labels:
      - "dependencies"
      - "java"
      - "maven"
    # PRの割り当て設定
    assignees:
      - "TakuyaFukumura"
    # PRテンプレートの設定
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    # 更新対象の設定
    open-pull-requests-limit: 5
    # セキュリティアップデートも含める
    insecure-external-code-execution: deny
