name: Dependabot PR Setup
# Dependabot PRに日本語レビューコメントを自動追加

on:
  pull_request:
    types: [opened]

jobs:
  setup-dependabot-pr:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    
    steps:
      - name: Add Japanese review comment to Dependabot PR
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            
            const japaneseComment = "<!-- 日本語でレビューして下さい -->";
            
            // PRの説明に日本語コメントが含まれていない場合は追加
            if (!pullRequest.body || !pullRequest.body.includes(japaneseComment)) {
              const newBody = japaneseComment + "\n\n" + (pullRequest.body || "");
              
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                body: newBody
              });
            }
      
      - name: Add labels to Dependabot PR
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['dependencies', 'java', 'maven', 'dependabot']
            });
